rbacApiVersion: rbac.authorization.k8s.io
namespace: operator-lifecycle-manager
catalog_namespace: operator-lifecycle-manager
operator_namespace: operators
minKubeVersion: 1.11.0
olmVersion: 0.17.0
debug: false
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 160Mi

catalog:
  replicaCount: 1
  commandArgs: -configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
  image:
    ref: quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 80Mi

package:
  replicaCount: 2
  image:
    ref: quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
    pullPolicy: IfNotPresent
  service:
    internalPort: 5443
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 50Mi
